[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.dependencies]
serde = "1"
holochain_serialized_bytes = "*"
hdi = "0.6.3"
hdk = { version = "0.5.3", features = [ "unstable-functions" ] }

[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"
