[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.dependencies]
serde = "1.0.193"
hdi = "0.6.0"
hdk = { version = "0.5.0", features = [ "unstable-functions" ] }

[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"
