[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.dependencies]
serde = "1.0.193"
hdi = "0.5.0-rc"
hdk = "0.4.0-rc"
holochain = "0.4.0-rc"

[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"
