[package]
name = "profiles_provider_zome_trait"
version = "0.1.0"
edition = "2024"

[dependencies]
hc_zome_traits = { git = "https://github.com/holochain-open-dev/zome-traits", branch = "main" }
hdk = "0.5"
holochain_serialized_bytes = "*"
serde = "1"
